#!/bin/bash

deepspeed --include localhost:1,2,3,4,5,6,7 /your_data_path//code/LLaVA/llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed /your_data_path//code/LLaVA/scripts/zero2.json \
    --version v1 \
    --model_name_or_path /your_data_path//models/llava_v1_5_7b \
    --data_path /your_data_path//data/scienceqa/llava1.5_scienceqa_insturction_train_val2.json \
    --image_folder /your_data_path//data \
    --vision_tower /mnt/workspace/workgroup/honghaochen/output/llava/openai/clip_vit_large_patch14_336 \
    --pretrain_mm_mlp_adapter /your_data_path//models/llava_v1_5_7b/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 False \
    --fp16 True \
    --output_dir ./checkpoints/llava-v1.5-7b-lora-sqa-instruction-train-val2 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to none
